


exec-once = fcitx5 --replace -d
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = udiskie -N &
exec-once = waybar
exec-once = mako
exec-once = hyprpaper &
# exec-once = swww img ~/Pictures/YUME.jpg --resize crop

exec-once = swayosd-server

exec-once = flash
