# workspace name settings
workspace = 1, monitor:HDMI-A-1, defaultname:󰭠 1
workspace = 2, monitor:HDMI-A-1, defaultname:󰭠 2
workspace = 3, monitor:HDMI-A-1, defaultName:󰭠 3
workspace = 4, monitor:HDMI-A-1, defaultName:󰭠 4
workspace = 5, monitor:HDMI-A-1, defaultName:󰭠 5
workspace = 6, monitor:HDMI-A-1, defaultName:󰭠 6
workspace = 7, monitor:HDMI-A-1, defaultName:󰭠 7
workspace = 8, monitor:HDMI-A-1, defaultName:󰭠 8
workspace = 9, monitor:eDP-1, defaultName:󰭠 9 
workspace = 10, monitor:eDP-1, defaultName:󰭠 10


# wechat
windowrule {
    name = wechat
    match:initial_class = ^wechat$

    float = true
    size = 1000 700
    center = on
}

# QQ
windowrule {
    name = QQ
    match:initial_class = ^QQ$

    float = true
    size = 1000 700
    center = on
}

# Thunar
windowrule {
    name = Thunar
    match:initial_class = ^thunar$

    float = true
    size = 1000 700
    center = on
}

# Flclash
windowrule {
    name = flclash
    match:initial_class = ^com.follow.clash$

    float = true
    size = 1000 700
    center = on
}


# Gtkwave
windowrule {
    name = Gtkwave
    match:initial_class = ^gtkwave$

    float = true
    size = 1000 700
    center = on
}
