[opener]
edit = [
    { run = 'nvim "$@"', desc = "Edit with Neovim", block = true },
]

vlc = [
    { run = 'vlc "$@"', desc = "Play with VLC", block = true },
]

[open]
rules = [
    { mime = "text/*", use = "edit" },
    { mime = "application/json", use = "edit" },
    { mime = "application/x-shellscript", use = "edit" },
    { name = "*.md", use = "edit" },
    { name = "*.txt", use = "edit" },
    { name = "*.conf", use = "edit" },
    { name = "*.sh", use = "edit" },
    { name = "*.bash", use = "edit" },
    { name = "*.zsh", use = "edit" },
    { name = "*.lua", use = "edit" },
    { name = "*.json", use = "edit" },
    { name = "*.toml", use = "edit" },
    { name = "*.yaml", use = "edit" },
    { name = "*.yml", use = "edit" },
    { name = "*.xml", use = "edit" },
    { name = "*.html", use = "edit" },
    { name = "*.css", use = "edit" },
    { name = "*.js", use = "edit" },
    { name = "*.ts", use = "edit" },
    # 添加其他你想用nvim编辑的文件类型
    { name = "*.mp3", use = "vlc" },
    { name = "*.mp4", use = "vlc" },
    # { name = "*.avi", use = "vlc" },
    { name = "*.mkv", use = "vlc" },
    # { name = "*.webm", use = "vlc" },
    # { name = "*.flv", use = "vlc" },
    # { name = "*.mov", use = "vlc" },
    # { name = "*.wmv", use = "vlc" },
]
