# Basic settings
set -g mouse on # enable mouse support

set -g history-limit 10000 # enable unlimited scrollback history

set -g base-index 1 # start window numbering at 1
setw -g pane-base-index 1 # start pane numbering at 1

set -g renumber-windows on # renumber windows when one is closed

set-option -g status-keys emacs # use emacs keybindings in status line
set-option -g default-terminal "tmux-256color" # enable true color support in tmux
set-option -ga terminal-overrides ",xterm-256color:Tc" # enable true color support in tmux for xterm-256color
setw -g mode-keys vi # use vi keybindings in copy mode
set -g escape-time 10 # fix esc delay in vim



# Keybindings
set -g prefix C-a # change prefix key to Ctrl-a

bind C-a send-prefix # allow sending prefix with Ctrl-a
unbind-key -T copy-mode-vi v

bind-key -T copy-mode-vi v \
    send-keys -X begin-selection

bind-key -T copy-mode-vi 'C-v' \
    send-keys -X rectangle-toggle

bind-key -T copy-mode-vi y \
    send-keys -X copy-pipe-and-cancel "wl-copy | cliphist add"

bind-key -T copy-mode-vi MouseDragEnd1Pane \
    send-keys -X copy-pipe-and-cancel "wl-copy | cliphist add"

bind-key r source-file ~/.tmux.conf \; display "Config reloaded!" # reload config with prefix + r
bind '|' split-window -h -c '#{pane_current_path}' # split horizontally in current directory
bind - split-window -v -c '#{pane_current_path}' # split vertically in current directory

# use Alt + number to switch to windows 1-10
bind-key -n M-1 switch-client -t 1
bind-key -n M-2 switch-client -t 2
bind-key -n M-3 switch-client -t 3
bind-key -n M-4 switch-client -t 4
bind-key -n M-5 switch-client -t 5
bind-key -n M-6 switch-client -t 6
bind-key -n M-7 switch-client -t 7
bind-key -n M-8 switch-client -t 8
bind-key -n M-9 switch-client -t 9
bind-key -n M-0 switch-client -t 0

bind-key x command-prompt -p "Close window #" "kill-window -t %%"

# Status line
set -g status-position bottom
set -g status-justify left
set -g status-interval 5
set -g status-style bg=colour234,fg=colour245

set -g status-left-length 200

set -g status-left "#[fg=colour232,bg=colour226,bold] ❐ #S #[default]#(tmux ls -F '##{?session_attached,#[fg=white]#[bg=colour238]#[bold] ↑ ##S ,#[fg=white]#[bg=colour238] ##S }' | tr '\\n' ' ') "

setw -g window-status-separator " "
setw -g window-status-format "#[fg=white,bg=colour238] #I #W "
setw -g window-status-current-format "#[fg=black,bg=colour39,bold] #I #W "

set -g status-right-length 150
set -g status-right "#[fg=white,bg=black] | %H:%M | %d %b #[fg=white,bg=colour160,bold] #(whoami) #[fg=black,bg=white,bold] #h "

set -g status-left-style none
set -g status-right-style none
# Plugins

set -g @plugin 'tmux-plugins/tpm' # Tmux Plugin Manager
set -g @plugin 'tmux-plugins/tmux-sensible' # Sensible defaults for tmux

set -g @plugin 'tmux-plugins/tmux-yank' # tmux plugin for copying to system clipboard using wl-copy
set -g @plugin 'tmux-plugins/tmux-open' # tmux plugin to open highlighted text in the system's default application
set -g @plugin 'tmux-plugins/tmux-prefix-highlight' # tmux plugin to highlight the prefix key
set -g @plugin 'tmux-plugins/tmux-pain-control' # tmux plugin for easy pane resizing with vim-like keybindings
set -g @plugin 'tmux-plugins/tmux-autoreload' # tmux plugin to automatically reload tmux config when it changes
set -g @plugin 'lloydbond/tmux-floating-terminal' # tmux plugin to open floating terminals

## Plugins config
set -g @continuum-restore 'on' # automatically restore sessions on tmux start


run '~/.tmux/plugins/tpm/tpm' # Initialize TMUX plugin manager
